---
version: '3'

services:

  s1:
    image: poc-kamon-zipkin:1.0-SNAPSHOT
    environment:
      APPLICATION_NAME: service1
      ZOOKEEPER_ADDRESSES: zookeeper:2181
      CONSTRUCTR_ZOOKEEPER_PATH: /constructr-poc
    ports:
    - 9000:9000

  s2:
    image: poc-kamon-zipkin:1.0-SNAPSHOT
    environment:
      APPLICATION_NAME: service2
      ZOOKEEPER_ADDRESSES: zookeeper:2181
      CONSTRUCTR_ZOOKEEPER_PATH: /constructr-poc
    ports:
    - 9001:9000

  s3:
    image: poc-kamon-zipkin:1.0-SNAPSHOT
    environment:
      APPLICATION_NAME: service3
      ZOOKEEPER_ADDRESSES: zookeeper:2181
      CONSTRUCTR_ZOOKEEPER_PATH: /constructr-poc
    ports:
    - 9002:9000

  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - 2181:2181